/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      dsr_moveit_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      dsr_controller2:
        type: dsr_controller2/RobotController

      dsr_joint_trajectory:
        type: dsr_joint_trajectory/RobotController

      dsr_joint_publisher:
        type: joint_state_controller/JointStateController

      dsr_position_controller:
        type: forward_command_controller/ForwardCommandController

      dsr_effort_controller:
        type: forward_command_controller/ForwardCommandController

      cartesian_impedance_controller:
         type: cartesian_impedance_controller/CartesianImpedanceController

      motion_control_handle:
        type: cartesian_controller_handles/MotionControlHandle

  dsr_controller2:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        
  dsr_position_controller:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
      interface_name: position
        
  dsr_effort_controller:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
      interface_name: effort

  cartesian_impedance_controller:
    ros__parameters:
      end_effector_link: "link_6"
      robot_base_link: "base_link"
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        
      command_interfaces:
        - "effort"
  
      solver:
          error_scale: 0.5
  
      stiffness:
          trans_x: 3000.0
          trans_y: 3000.0
          trans_z: 3000.0
          rot_x: 100.0
          rot_y: 100.0
          rot_z: 100.0 

      state_interfaces:
        - position
        - velocity
        - effort

  motion_control_handle:
    ros__parameters:
      end_effector_link: "link_6"
      robot_base_link: "base_link"
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6

      state_interfaces:
        - position
        - velocity
        - effort
  
  dsr_joint_trajectory:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
  
      command_interfaces:
        - position
        - velocity
  
      state_interfaces:
        - position
        - velocity
  
  dsr_moveit_controller:
    ros__parameters:
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
  
